package com.zhang.spring.jsp.dao;

import com.zhang.spring.jsp.entity.UserTable;
import com.zhang.spring.jsp.entity.UserTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    long countByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int deleteByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int insert(UserTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int insertSelective(UserTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    List<UserTable> selectByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    UserTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserTable record, @Param("example") UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int updateByExample(@Param("record") UserTable record, @Param("example") UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int updateByPrimaryKeySelective(UserTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbg.generated Sat Dec 14 21:28:19 CST 2019
     */
    int updateByPrimaryKey(UserTable record);
}